<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TL1QD2K" failures="4" tests="26" name="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" time="0.108" errors="0" timestamp="2020-12-02T16:56:56 CET" skipped="1">
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="soustractionTest" time="0.003"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="multiplicationTest" time="0.009"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="multiplicationTest" time="0.003"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="divisionTestException" time="0.010"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="soustractionTest" time="0.006"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="divisionTest" time="0.006">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest.divisionTest(CalculetteTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:238)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:181)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:252)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:595)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at bstorm.akimt.demoTestNG.correction.prog.ExoProg.main(ExoProg.java:38)
]]>
    </failure>
  </testcase> <!-- divisionTest -->
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="multiplicationTest" time="0.004"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="soustractionTest" time="0.001"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="multiplicationTest" time="0.002"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="additionTest" time="0.003"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="soustractionTest" time="0.003"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="divisionTest" time="0.000">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest.divisionTest(CalculetteTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:238)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:181)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:252)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:595)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at bstorm.akimt.demoTestNG.correction.prog.ExoProg.main(ExoProg.java:38)
]]>
    </failure>
  </testcase> <!-- divisionTest -->
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="additionTest" time="0.021"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="multiplicationTest" time="0.003"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="operationTest" time="0.003">
    <skipped/>
  </testcase> <!-- operationTest -->
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="additionTest" time="0.002"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="soustractionTest" time="0.003"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="operationTestException" time="0.002"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="soustractionTest" time="0.002"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="additionTest" time="0.001"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="additionTest" time="0.009"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="additionTest" time="0.004"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="divisionTest" time="0.001">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest.divisionTest(CalculetteTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:238)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:181)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:252)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:595)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at bstorm.akimt.demoTestNG.correction.prog.ExoProg.main(ExoProg.java:38)
]]>
    </failure>
  </testcase> <!-- divisionTest -->
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="multiplicationTest" time="0.004"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="multiplicationTest" time="0.002"/>
  <system-out/>
  <testcase classname="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest" name="divisionTest" time="0.001">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest.divisionTest(CalculetteTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:238)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:181)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:252)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:595)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at bstorm.akimt.demoTestNG.correction.prog.ExoProg.main(ExoProg.java:38)
]]>
    </failure>
  </testcase> <!-- divisionTest -->
  <system-out/>
</testsuite> <!-- bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest -->
